version: "3.8"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    command: bash -c 'pip3 install -r requirements.txt && ./run.sh'