# Generated by Django 3.2.5 on 2022-07-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('blog_image_url', models.URLField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, max_length=500, null=True)),
                ('author_image_url', models.URLField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=500, null=True)),
                ('reading_time', models.CharField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
